ejm_flow_data_graph:
    path:     /graphs
    defaults: { _controller: EJMFlowBundle:Data:graph }

ejm_flow_data_validation:
    path:     /validation
    defaults: { _controller: EJMFlowBundle:Data:validation }
