parameters:
    mapper.config:
        map_handlers: true
        map_subscribers: true

services:
    flow.mapper:
        alias: 'flow.mapper.d3.force_layout_mapper'

    flow.mapper.d3.force_layout_mapper:
        class: EJM\Flow\Mapper\D3\ForceLayoutMapper
        arguments:
            - '%mapper.config%'

    flow.network:
        class: EJM\Flow\Network\Network
        factory: ['@flow.network.builder', 'build']

    flow.network.builder:
        class: EJM\Flow\Network\Builder
        public: false

    flow.network.builder.stage.add_commands_and_handlers:
        class: EJM\Flow\Network\Builder\AssemblyStage\AddCommandsAndHandlers
        public: false
        arguments:
            - '%flow.map.command_handler%' # defined in registerHandlers compiler pass
        tags:
            - { name: flow.assembly_stage }

    flow.network.builder.stage.add_events_and_subscribers:
        class: EJM\Flow\Network\Builder\AssemblyStage\AddEventsAndSubscribers
        public: false
        arguments:
            - '%flow.map.events_subscribers%' # defined in registerSubscribers compiler pass
        tags:
            - { name: flow.assembly_stage }

    flow.network.builder.stage.add_published_messages:
        class: EJM\Flow\Network\Builder\AssemblyStage\AddPublishedMessages
        public: false
        arguments:
            - '@flow.collector.messages_to_publish'
        tags:
            - { name: flow.assembly_stage }

    flow.network.splitter:
        class: EJM\Flow\Network\Splitter

    flow.collector.messages_to_publish:
        class: EJM\Flow\Collector\MessagesToPublishCollector

    flow.validator:
        class: EJM\Flow\Validator\Validator

    flow.validator.constraint.handler_triggers_command:
        class: EJM\Flow\Validator\Constraint\HandlerTriggersCommand
        public: false
        tags:
            - { name: flow.validator_constraint }

    flow.validator.constraint.event_without_subscriber:
        class: EJM\Flow\Validator\Constraint\EventWithoutSubscriber
        public: false
        tags:
            - { name: flow.validator_constraint }
